### ISSUE TITLE
Gestion des droits pour les comptes

### ISSUE THREAD

**Issue by bigred38** [InfotelGLPI/accounts#10]
Bonjour,

Nous utilisons GLPI 0.85.4 et le plugin account.
Les comptes sont reliés à des serveurs (ordinateur).
En fonction ne nos droits  on voit ou pas les comptes.

Si je vais dans mon_url/front/computer.form.php?id=2063, je ne vois pas les comptes.
Par contre si je connais id du compte et que je vais sur mon_url/plugins/accounts/front/account.form.php?id=1780 et que je rentre la clé de chiffrement, je peux voir le mot de passe.

Est une erreur de configuration ou est ce un bug?

**Comment by bigred38** [comment]
Anybody

**Comment by amma35** [comment]
This bug is not present in version [2.3.1](https://github.com/InfotelGLPI/accounts/releases/tag/2.3.1)
Version 0.85 is no longer maintained
