### ISSUE TITLE
Warning DbUtils.php at line 2111 Invalid relations

### ISSUE THREAD

**Issue by sina-4** [InfotelGLPI/accounts#100]
I'm currently using GLPI version 10.0.10, and I've encountered a recurring warning message that disappears after a few seconds:

PHP user warning (512) : Invalid relations declared for "glpi_plugin_accounts_accountstates" table. Target table "glpi_plugin_accounts_mailingstates" does not correspond to a known itemtype. in /var/www/html/glpi10/src/DbUtils.php at line 2111

I've already verified the integrity of the database, and everything appears to be in order. However, I'm still experiencing this warning. Can someone provide assistance or guidance on resolving this issue?

* Version of the plugin : 3.0.3

* Version of your GLPI : 10.0.10

**Comment by hgpit** [comment]
Also seeing this alot:
`[2023-10-18 16:20:22] glpiphplog.WARNING:   *** PHP User Warning (512): Relation between "glpi_networkports" and "glpi_plugin_ocsinventoryng_networkports" table based on "networkports_id" field cannot be handled automatically as "networkports_id" also corresponds to index field of the target table. in /var/www/helpdesk.my-domain.local/src/DbUtils.php at line 2131
  Backtrace :
  src/DbUtils.php:2131                               trigger_error()
  inc/db.function.php:585                            DbUtils->getDbRelations()
  src/CommonDBTM.php:866                             getDbRelations()
  src/CommonDBTM.php:788                             CommonDBTM->cleanRelationData()
  ajax/unlockobject.php:57                           CommonDBTM->deleteFromDB()
  public/index.php:82                                require()

[2023-10-18 16:20:22] glpiphplog.WARNING:   *** PHP User Warning (512): Invalid relations declared for "glpi_plugin_accounts_accountstates" table. Target table "glpi_plugin_accounts_mailingstates" does not correspond to a known itemtype. in /var/www/helpdesk.my-domain.local/src/DbUtils.php at line 2111
  Backtrace :
  src/DbUtils.php:2111                               trigger_error()
  inc/db.function.php:585                            DbUtils->getDbRelations()
  src/CommonDBTM.php:866                             getDbRelations()
  src/CommonDBTM.php:788                             CommonDBTM->cleanRelationData()
  ajax/unlockobject.php:57                           CommonDBTM->deleteFromDB()
  public/index.php:82                                require()

[2023-10-18 16:20:52] glpiphplog.WARNING:   *** PHP User Warning (512): Relation between "glpi_networkports" and "glpi_plugin_ocsinventoryng_networkports" table based on "networkports_id" field cannot be handled automatically as "networkports_id" also corresponds to index field of the target table. in /var/www/helpdesk.my-domain.local/src/DbUtils.php at line 2131
  Backtrace :
  src/DbUtils.php:2131                               trigger_error()
  inc/db.function.php:585                            DbUtils->getDbRelations()
  src/CommonDBTM.php:866                             getDbRelations()
  src/CommonDBTM.php:788                             CommonDBTM->cleanRelationData()
  ajax/unlockobject.php:57                           CommonDBTM->deleteFromDB()
  public/index.php:82                                require()

[2023-10-18 16:20:52] glpiphplog.WARNING:   *** PHP User Warning (512): Invalid relations declared for "glpi_plugin_accounts_accountstates" table. Target table "glpi_plugin_accounts_mailingstates" does not correspond to a known itemtype. in /var/www/helpdesk.my-domain.local/src/DbUtils.php at line 2111
  Backtrace :
  src/DbUtils.php:2111                               trigger_error()
  inc/db.function.php:585                            DbUtils->getDbRelations()
  src/CommonDBTM.php:866                             getDbRelations()
  src/CommonDBTM.php:788                             CommonDBTM->cleanRelationData()
  ajax/unlockobject.php:57                           CommonDBTM->deleteFromDB()
  public/index.php:82                                require()
`

It's generating GB's and GB's of log file.

**Comment by ToFz80** [comment]
Hi

I have the same problem with GLPI 10.0.10 and Plugin account 3.0.3

**Comment by tsmr** [comment]
Fixed into las version
