### ISSUE TITLE
Drop usage of very old methods

### ISSUE THREAD

**Issue by trasher** [InfotelGLPI/accounts#11]
Hi,

It seems the plugin actually uses methods in core that should have been deprecated (some parts were) and are going to be removed in 9.2 (see https://github.com/glpi-project/glpi/pull/1901).

**Comment by tsmr** [comment]
Thanks for your ticket, we will do the job asap

**Comment by tsmr** [comment]
I found only addDivForTabs call but already commented.

So no problem
