### ISSUE TITLE
Can't update encryption key

### ISSUE THREAD

**Issue by TarasSavchuk** [InfotelGLPI/accounts#13]
Hi,

I have fresh GLPI 9.1.2 + Accounts plugin 2.2.0 installed.
After creating Encryption key I can't change it any more.
No error messages. Browser tells me key is updated, but it's not - in glpi_plugin_accounts_hashes hash is same. 
Also tested with latest 5c6fac0c40803ba57ae607ddefc624c8ff041418 - same problem.

**Comment by amma35** [comment]
Hi,

Do you have errors in the log files in glpi/files/_log/php-errors.log and sql-errors.log ?

**Comment by TarasSavchuk** [comment]
Nope :)

--
Taras Savchuk

**Comment by amma35** [comment]
Do you use the section "Modification of the encryption key"?

**Comment by amma35** [comment]
I'm closing for now without answer, feel free to reopen if issue persists.
