### ISSUE TITLE
Import en masse

### ISSUE THREAD

**Issue by xlelievre** [InfotelGLPI/accounts#14]
Bonjour,
Je cherche à importer plus de 1000 comptes.
J'ai pu écrire le tableau d'import, mais je ne sais pas comment importer les mot de passe.
Faut-il les importer crypter ? Dans ce cas comment je peux les crypter?
Y a t-il une fonction qui le permette une fois les comptes importé ?

Merci d'avance
Xavier

**Comment by Jugurtha13** [comment]
Bonjour,
Je suis dans le même cas, j'ai environ 2000 comptes à importer.
j'ai testé ceci mais sans succès pour moi malheureusement.

`$oldpassword = 'passwdtest;
$newhash='xxxxx0da6b1428b93b9589d24f029d32c96e7905382f23d670xxxxxxxxxxxxxxxxxxxxxx';   //hash récupérer depuis cette table : glpi_plugin_accounts_hashes
// idem avec $newhash='masuperclé';
$newpassword=addslashes(plugin_accounts_AESEncryptCtr($oldpassword, $newhash, 256));
echo "NEW PASSWORD : " . $newpassword;`

Si vous pouvez-nous mettre sur la piste ca serait super.
Merci d'avance pour votre aide.

**Comment by Jugurtha13** [comment]
J'ai trouvé, je dépose la solution à ceux qui auront le même besoin.
$password = 'chaineACrypter';
$aeskey = "Le clé AES"
passCrypte = AESEncryptCtr("$password",SHA256("$aeskey"), 256);

Même principe pour la fonction AESDecryptCtr
