### ISSUE TITLE
Problem with account

### ISSUE THREAD

**Issue by Val9171** [InfotelGLPI/accounts#15]
Hello
My version of glpi is 9.1.3
My plugin is 2.2.0
![capture-glpi-1](https://cloud.githubusercontent.com/assets/28900533/26361835/78f420b8-3fdc-11e7-8982-ef699ca43e8a.gif)
![capture-glpi-2](https://cloud.githubusercontent.com/assets/28900533/26361834/78c7aaec-3fdc-11e7-8274-b69b1dbc74f2.gif)
"comptes" is not clickable and there is no encryption key
Haw can i proceed to correct this problem?
Thank you

**Comment by amma35** [comment]
Hi,

This is found in Administration> Accounts : 
![2017-05-23 17_40_16-glpi - comptes](https://cloud.githubusercontent.com/assets/15138371/26362807/6e186872-3fdf-11e7-86ce-d63f5e10558c.png)

**Comment by Val9171** [comment]
Merci, j'ai pu créer la clé de chiffrement, en revanche le plugin "comptes" n'est toujour pas cliquable, est-ce normal?
![capture-glpi-1](https://cloud.githubusercontent.com/assets/28900533/26363580/be409bce-3fe1-11e7-9b63-4880c167c9c6.gif)

**Comment by amma35** [comment]
Oui c'est normal, il n'y a pas de configuration dans le plugin.

**Comment by Val9171** [comment]
Merci 😉

De : Amandine Manceau [mailto:notifications@github.com]
Envoyé : mardi 23 mai 2017 18:03
À : InfotelGLPI/accounts <accounts@noreply.github.com>
Cc : Valerie BEUNARDEAU <communication@solution404.com>; Author <author@noreply.github.com>
Objet : Re: [InfotelGLPI/accounts] Problem with account (#15)


Oui c'est normal, il n'y a pas de configuration dans le plugin.
