### ISSUE TITLE
Security die. trying to load an forbidden class name

### ISSUE THREAD

**Issue by AliouneDiop** [InfotelGLPI/accounts#18]
Dear
I have this error Security die. trying to load an forbidden class name with the plugin accounts. When i changed the number of items to display from 15 to 40 or more, I received the error. I m using GLPI version 9.1.3
Thanks for your support

**Comment by amma35** [comment]
Hi,

Can you give exacts errors in glpi php-errors.log?

**Comment by AliouneDiop** [comment]
Hi all
I solved the problem from the database.
They were some accounts with 0 in the itemstype colomn.I just set it
Entity( default entity), updated the database and it worked fine without
error.
thanks

**Comment by amma35** [comment]
Ok thank you for your return.
