### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to a member function fetch_assoc() Using Plugin

### ISSUE THREAD

**Issue by akira345** [InfotelGLPI/accounts#20]
Hi.
I'm using GLPI.
I found an error in the Apache log.
`[Mon Aug 21 10:33:19 2017] [error] [client 192.168.x.xxx] PHP Fatal error:  Uncaught Error: Call to a member function fetch_assoc() on boolean in /var/www/html/GLPI/inc/dbmysql.class.php:308\nStack trace:\n#0 /var/www/html/GLPI/plugins/accounts/inc/account.class.php(729): DBmysql->fetch_assoc(false)\n#1 /var/www/html/GLPI/plugins/accounts/inc/account_item.class.php(514): PluginAccountsAccount::dropdownAccount(Array)\n#2 /var/www/html/GLPI/plugins/accounts/inc/account_item.class.php(134): PluginAccountsAccount_Item::showForItem(Object(Computer))\n#3 /var/www/html/GLPI/inc/commonglpi.class.php(483): PluginAccountsAccount_Item::displayTabContentForItem(Object(Computer), '1', '')\n#4 /var/www/html/GLPI/ajax/common.tabs.php(97): CommonGLPI::displayStandardTab(Object(Computer), 'PluginAccountsA...', '', Array)\n#5 {main}\n  thrown in /var/www/html/GLPI/inc/dbmysql.class.php on line 308, referer: http://192.168.xxx.xxx/GLPI/front/computer.form.php?id=263`

This error makes the account display loading forever.
![error](https://user-images.githubusercontent.com/655764/29500700-1e12b894-865e-11e7-9a8e-adb1ce2de0d3.jpg)
I have one hint.
It happens when the authority is "super-admin", it does not occur if it is "normal".

OS:CentOS release 6.9 (Final)
GLPI:9.1.6
Plugin:2.2.0
PHP:7.0.22 (cli) (built: Aug  2 2017 14:07:24) ( NTS )

What's the problem??

**Comment by amma35** [comment]
Can you give errors in glpi files/_logs/sql-errors.log ?

**Comment by akira345** [comment]
Hi.
I get sql-errors.log

2017-09-14 17:15:43 [24@localhost.localdomain]
  *** MySQL query error:
  SQL: SELECT *
                FROM `glpi_plugin_accounts_accounttypes`
                WHERE `id` IN (SELECT DISTINCT `plugin_accounts_accounttypes_id`
                               FROM `glpi_plugin_accounts_accounts`
                              WHERE `glpi_plugin_accounts_accounts`.`is_deleted` = \'0\' AND ( `glpi_plugin_accounts_accounts`.`entities_id` = \'0\'  )  AND `id` NOT IN (0, ,862,863,884,864,861,857,895,897))
                ORDER BY `name`
  Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '862,863,884,864,861,857,895,897))
                ORDER BY `name`' at line 5
  Backtrace :
  plugins/accounts/inc/account.class.php:725         
  plugins/accounts/inc/account_item.class.php:514    PluginAccountsAccount::dropdownAccount()
  plugins/accounts/inc/account_item.class.php:134    PluginAccountsAccount_Item::showForItem()
  inc/commonglpi.class.php:483                       PluginAccountsAccount_Item::displayTabContentForItem()
  ajax/common.tabs.php:97                            CommonGLPI::displayStandardTab()


MySQL version of this server is 
mysql  Ver 14.14 Distrib 5.1.73, for redhat-linux-gnu (x86_64) using readline 5.1

**Comment by amma35** [comment]
Still the mistake?

I tried to reproduce with the SQL error I do not get this bug.

**Comment by jpsbatista** [comment]
Olá @amma35 
Tenho problema acredito que deva ser o mesmo do @akira345 .

mailgate fica como executando

nos logs da tarefa do cron.php recebo o seguinte erro:
PHP Fatal error:  Uncaught Error: Call to a member function free() on boolean in
 D:\xampp\htdocs\glpi\inc\dbmysql.class.php:432
Stack trace:
#0 D:\xampp\htdocs\glpi\inc\dbmysql.class.php(741): DBmysql->free_result(false)
#1 D:\xampp\htdocs\glpi\inc\dbmysql.class.php(757): DBmysql->tableExists('glpi_e
ntities')
#2 D:\xampp\htdocs\glpi\inc\dbutils.class.php(798): DBmysql->fieldExists('glpi_e
ntities', 'ancestors_cache')
#3 D:\xampp\htdocs\glpi\inc\dbutils.class.php(558): DbUtils->getAncestorsOf('glp
i_entities', '5')
#4 D:\xampp\htdocs\glpi\inc\db.function.php(739): DbUtils->getEntitiesRestrictRe
quest(' WHERE', 'glpi_groups', '`glpi_groups`.`...', '5', true, false)
#5 D:\xampp\htdocs\glpi\inc\notificationtarget.class.php(774): getEntitiesRestri
ctRequest(' WHERE', 'glpi_groups', 'entities_id', '5', true)
#6 D:\xampp\htdocs\glpi\inc\notificationtarget.class.php(813): NotificationTarge
t->addGroupsToTargets('5')
#7 D:\xampp\htdocs\glpi\inc\notificationtarget.class.php(130): NotificationTarge
t->addNotificationTargets('5')
#8 D:\xampp\ht in D:\xampp\htdocs\glpi\inc\dbmysql.class.php on line 432


Em sql-error, recebo o seguinte:
Não foi possível adquirir bloqueio do DB

**Comment by amma35** [comment]
You have to open a new issue and write in English. Thank you

**Comment by wellington1993** [comment]
Hi,

I  have the same problems:

`[Thu Apr 05 17:32:04.139957 2018] [:error] [pid 1042] [client 192.168.200.45:53604] PHP Fatal error:  Uncaught Error: Call to a member function showhbar() on null in /var/www/html/glpi/plugins/mreporting/inc/common.class.php:640\nStack trace:\n#0 /var/www/html/glpi/plugins/mreporting/front/graph.php(42): PluginMreportingCommon->showGraph(Array)\n#1 {main}\n  thrown in /var/www/html/glpi/plugins/mreporting/inc/common.class.php on line 640, referer: http://192.168.200.231/glpi/plugins/mreporting/front/graph.php?short_classname=Helpdesk&f_name=reportHgbarOpenTicketNumberByCategoryAndByType&gtype=hgbar`

Any idea?

Thanks!

**Comment by amma35** [comment]
You need to write a new issue because I don't think your problem is related to the display of computers and you explain your problem a little more if you want help.
