### ISSUE TITLE
Wrong encryption key

### ISSUE THREAD

**Issue by grazzianos** [InfotelGLPI/accounts#25]
Hello folks.

I'm using GLPI version 9.2.1 and Account Plugin version 2.3.1. For protection purposes, I'm using more than one encryption key (one for Infrastructure Admins and another to Normal Admin users - we have two levels of user profiles).

First, I started adding both keys, then after that, the accounts. To reproduce the error, I start adding the accounts with the "normal" key, and after, accounts with "infrastructure" key. After add accounts with both keys, I add a new one with "normal" key, and I received the "Wrong Encryption Key" error. I think the code only verifies the last inserted encryption key, and decode the new accounts only with this last key.

I started to analise the code and database and saw no association between the accounts and keys at database level. Maybe because of this, the code only correctly decode with the last key.

Is there a way to display some accounts to specific groups of users and use more than one key?

Can someone help me?

**Comment by amma35** [comment]
Hi,

Only one encryption key can be created per entity.

You would have to go through development to add the functionality of adding multiple encryption keys per entity and assign either to a group or profile...

**Comment by amma35** [comment]
I'm closing for now without answer
