### ISSUE TITLE
Access to releases for GLPI v0.84.x

### ISSUE THREAD

**Issue by phaworth** [InfotelGLPI/accounts#27]
I'm trying to carefully upgrade an old GLPI installation with a few plugins in, firstly to version 0.84. Unfortunately your releases only go back to v2.0.1 for v0.85 - is there anywhere else I can go to get at older releases?

Thanks

**Comment by amma35** [comment]
see https://forge.glpi-project.org/projects/accounts/files

**Comment by phaworth** [comment]
Cheers
