### ISSUE TITLE
Problem with "plugins/accounts/inc/account.class.php"

### ISSUE THREAD

**Issue by fplancot** [InfotelGLPI/accounts#29]
* Version of the plugin : 2.3.0 et 2.3.1

* Version of your GLPI : 9.2.2

* Steps to reproduce (which actions have you made) : N/A

* Expected result :
![with correction](https://user-images.githubusercontent.com/3037354/39043754-88687302-448e-11e8-8f75-aca2e17e9eb4.PNG)

* Actual result :
![error](https://user-images.githubusercontent.com/3037354/39043774-913e0faa-448e-11e8-93da-2ab6b58ba29f.PNG)

* URL of the page : 
http://<servername>/glpi/front/computer.form.php?id=<??>
Tabs "Compte"

* Screenshot of the problem (if pertinent) :
Below, the contents of the log file.
![errormsg](https://user-images.githubusercontent.com/3037354/39048509-ffd693c4-449d-11e8-9bad-56d3a511b5cb.PNG)

* Proposed correction

Modify line 714 in "plugins/accounts/inc/account.class.php" :
```php
$where .= " AND `id` NOT IN (0, " . implode(",", $p['used']) . ")";
```
by
```php
$where .= " AND `id` NOT IN (0, " . implode(",", array_filter($p['used'])) . ")";
```

**Comment by amma35** [comment]
This correction makes it possible to compensate if there was a problem in the present accounts.

But the first problem is how can you have an account in this computer that doesn't exist?
