### ISSUE TITLE
Mot de passe encrypté avec nouvelle clé, se décrypte avec ancienne clé

### ISSUE THREAD

**Issue by belu33fr** [InfotelGLPI/accounts#34]
Dear GLPi user.

BEFORE SUBMITTING YOUR ISSUE, please make sure to read and follow these steps :

* Verify that your question has not already been asked
* Please use the below template.
* Delete this text before submiting your issue.

The Plugin team.

------------
* Version of the plugin : 2.3.2

* Version of your GLPI : 9.2.1

* Steps to reproduce (which actions have you made) :
Créer une entité et une sous entité
Créer une clé dans l'entité avec propagation aux sous entités
Créez un compte utilisant cette clé dans l'entité et la sous entité
Changer la valeur de la clé (modification de clé)
Aller dans la sous entité
Ouvrir le compte et dechiffrer le mot de passe avec la nouvelle clé (l'ancienne ne marche plus)
Changer à nouveau la valeur de la clé (modification de clé) avec l'ancienne valeur

* Expected result :
Une valeur encryptée de mot de passe  mdp->encryptage->encryptage=>pas mdp

* Actual result :
La valeur en clair du mot de passe

* URL of the page :

* Screenshot of the problem (if pertinent) :

**Comment by amma35** [comment]
Same 41ffbf1
