### ISSUE TITLE
Multi-clés

### ISSUE THREAD

**Issue by belu33fr** [InfotelGLPI/accounts#36]
Dear GLPi user.

BEFORE SUBMITTING YOUR ISSUE, please make sure to read and follow these steps :

* Verify that your question has not already been asked
* Please use the below template.
* Delete this text before submiting your issue.

The Plugin team.

------------
* Version of the plugin : 2.3.2

* Version of your GLPI : 9.2.1

* Steps to reproduce (which actions have you made) :
Créer une entité
Créer une clé dans l'entité
Créez un ou plusieurs comptes utilisant cette clé dans l'entité
Créer une clé supplémentaire dans l'entité
Créez un ou plusieurs comptes utilisant cette clé dans l'entité
Créer un compte avec la première clé

* Expected result :
Création du compte

* Actual result :
Clé non valide

* Remarque: Si vous faites la lecture des comptes le problème est le même pour le décryptage avec l'autre clé

* URL of the page :

* Screenshot of the problem (if pertinent) :

**Comment by amma35** [comment]
It is not possible to create multiple keys for a single entity.
Warning message :
![accounts](https://user-images.githubusercontent.com/15138371/42829481-006bc606-89ea-11e8-99c7-01af4f4a75cc.png)

Specific development is needed to change this behaviour.

**Comment by belu33fr** [comment]
May be. Never I had a message with the steps. Just I try again, I have no message and the new encryption key is created….

**Comment by belu33fr** [comment]
Question: Why, if it not possible to create a double key, really you can.
![image](https://user-images.githubusercontent.com/40408529/43040005-80084fcc-8d39-11e8-89a0-695ad2d05b3d.png)

**Comment by amma35** [comment]
You can create as many keys as you want but the plugin will no longer work for the other steps for account passwords.
He will not know which key to use because only one key must be created per entity and care must be taken with the parent entities.

**Comment by belu33fr** [comment]
Sorry about my answer delay
I understand. This is a real issue because you can create many key but the plugin can not work fine with them. You can solve this situation, because the plugin accept to work with only one key, you need control and deny to create many key…..
