### ISSUE TITLE
Form misbehaviour in Chrome

### ISSUE THREAD

**Issue by hgpit** [InfotelGLPI/accounts#37]
GLPI 9.2.3
Accounts 2.3.2
Chrome 67.0.3396.87 (Official Build) (64-bit)

Firefox is fine.

When I click seemingly anywhere on the form to edit an account, the 'Affected User' drop-down misbehaves and tries to take focus. It overlaps and interferes with the browser view.

Chrome console reports:
![image](https://user-images.githubusercontent.com/16598973/41654245-ba776304-7480-11e8-8230-8965b4cbc535.png)

Sorry if this is a known bug.

Chrome is the preferred browser for our organization, so it would be nice if it could be fixed.

All other areas/forms of our GLPI work perfectly in the same version of Chrome.

Thank you.

**Comment by amma35** [comment]
Hi,

We use GLPI's core methods, unfortunately we have no corrections to make.
However with GLPI version 9.3, there is no longer this problem.
