### ISSUE TITLE
Incompatibility with GLPI 9.3

### ISSUE THREAD

**Issue by havas-datait** [InfotelGLPI/accounts#38]
Hi Plugin Team,
Thank you for your work on this plugin. We encounter an incompatibility issue with GLPI 9.3 which prevents us to install it on our new GLPI server.
Thank you in advance for your help.

------------
* Version of the plugin :  2.3.2
* Version of your GLPI : 9.3
* Steps to reproduce (which actions have you made) :
Try to install the 2.3.2 version on GLPI 9.3
* Expected result :
Plugin "installable".
* Actual result :
Incompatibility message: "Ce plugin nécessite GLPI >= 9.2".

**Comment by amma35** [comment]
see https://github.com/InfotelGLPI/accounts/releases/tag/2.4.0

**Comment by havas-datait** [comment]
Thank you very much for your help and your responsiveness!
