### ISSUE TITLE
GLPI 0.90 - impossible d'accèder aux réglages.

### ISSUE THREAD

**Issue by Oyabi** [InfotelGLPI/accounts#4]
Bonjour,
je ne peux pas accèder au réglages du plugins sur la version 0.90 de GLPI.
Si je vais dans Configuration -> Plugins et que je l'active, je n'ai pas de lien me conduisant à la apge de génération de clef que ce soit sur cette même page ou bien dans le menu Plugins.
Le problème a lieu avec FIrefox 42 et Chrome 46, je n'ai pas testé avec IE.
Pouvez-vous m'indiquer la marche à suivre pour corriger le problème svp ?

Cordialement.

**Comment by tsmr** [comment]
Pouvez vous me donner vos versions de GLPI et du plugin d'origine ?

**Comment by Oyabi** [comment]
Bien sur : 
- GLPI 0.90
- Comptes 2.1.1

Merci.

**Comment by tsmr** [comment]
Non c'est une migration depuis une ancienne version si oui lesquelles ? ou une nouvelle installation ?

**Comment by Oyabi** [comment]
Ah, mon installation de glpi est une migration (0.84.5), mais c'est la premiere fois que j'installe votre module.

**Comment by tsmr** [comment]
Depuis la liste des comptes, cliquer sur le cadenas ?

![image](https://cloud.githubusercontent.com/assets/13178158/10975169/e2bb6f38-83e5-11e5-9418-fde3b1d74ef6.png)

**Comment by Oyabi** [comment]
Oh....
Merci :D, je pensais vraiment voir un sous-menu dans Plugin ou bien pouvoir cliquer sur Comptes comme sur cette image dans la doc.
https://github.com/InfotelGLPI/accounts/blob/master/wiki/accounts2.png
Merci encore une fois.
