### ISSUE TITLE
No more accounts list appearing

### ISSUE THREAD

**Issue by Clemt58** [InfotelGLPI/accounts#41]
Hello,

I've updated GLPI (ubuntu-server) with 9.3.1 version, and accounts plugin with 2.4.2 version, since these upgrade it seems that I've lost all the old accounts entries. How can I retreive them ?

Thanks

**Comment by Clemt58** [comment]
Hello,

I've updated GLPI (ubuntu-server) with 9.3.1 version, and accounts plugin with 2.4.2 version, since these upgrade it seems that I've lost all the old accounts entries. How can I retreive them ?

Thanks

**Comment by amma35** [comment]
Hi,
If you haven't made a backup and the data is no longer present, it isn't possible to recover the data.

First you have to check in SQL if in the tables `glpi_plugin_accounts_accounts` if you have data.

**Comment by Clemt58** [comment]
Indeed the table is empty. I'll see if I've a backup to restore the data.

Thanks.
