### ISSUE TITLE
Plantage glpi 9.3.1

### ISSUE THREAD

**Issue by slysmith** [InfotelGLPI/accounts#44]
Bonjour,

J'ai installé la maj GLPI 9.3 > 9.3.1 tout est OK..... sauf pour le plugin accounts si je l'active je n'arrive même plus à atteindre la page d'accueil de GLPI....

Je me sers beaucoup de ce plugin en prod chez mes clients est il possible de voir d'où vient le problème ?

Merci

**Comment by amma35** [comment]
Bonjour,

Erreur PHP, SQL (/glpi/files/_log/php-errors.log ou sql-errors.log), erreur apache ?

**Comment by slysmith** [comment]
je vois cette erreur se répéter inlassablement dans php-errors.log je ne sais pas si c'est ça le problème :

:
  inc/plugin.class.php:248                           readdir()
  inc/plugin.class.php:402                           Plugin->checkStates()
  front/plugin.php:91                                Plugin->listPlugins()
  {"user":"2@GLPI","mem_usage":"0.000\", 2.02Mio)"}
[2018-10-26 15:12:03] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/html/glpi/inc/toolbox.class.php line 657
  *** PHP Warning(2): readdir() expects parameter 1 to be resource, boolean given

**Comment by slysmith** [comment]
Mes autres plugins ont redémarrés sans soucis (fusion inventory et dashboard) il n y'a que celui ci qui fait tout planter....

**Comment by slysmith** [comment]
voila le soucis dans les log apache2 : 

 PHP Fatal error:  Access level to PluginAccountsAccount_Item::countForItem() must be public (as in class CommonDBRelation) in /var/www/html/glpi/plugins/ac$$ins/accounts/inc/account_item.class.php on line 38, referer: http://192.168.1.75/glpi/index.php

**Comment by amma35** [comment]
Version du plugin ?

**Comment by slysmith** [comment]
c'est la version 2.4.1

**Comment by slysmith** [comment]
tout est OK j'ai utilisé la version 2.4.2 ça fonctionne.

Merci
