### ISSUE TITLE
Version 2.4.3

### ISSUE THREAD

**Issue by Phorms** [InfotelGLPI/accounts#48]
* Version of the plugin : 
2.4.3

* Version of your GLPI : 
9.3.3

* Steps to reproduce (which actions have you made) :
Download https://github.com/InfotelGLPI/accounts/releases/download/2.4.3/glpi-accounts.2.4.3.tar.gz

* Expected result :
Get version 2.4.3

* Actual result :
Got version 2.5.0

The file glpi-accounts.2.4.3.tar.gz contains version 2.5.0 not 2.4.3!

**Comment by keha35** [comment]
Hi,

Thanks for noticing this error.
I'm updating the file.

Br.
