### ISSUE TITLE
Plugin configuration not a link on GLPI 0.90.1

### ISSUE THREAD

**Issue by rraub** [InfotelGLPI/accounts#5]
Just installed this accounts plugin on GLPI v0.90.1 and there is no link to the plugin configuration after activation.
![screen shot 2015-12-04 at 10 59 50 am](https://cloud.githubusercontent.com/assets/295804/11597045/2df0a92c-9a76-11e5-870f-bfbe36d1cdd6.png)

**Comment by tsmr** [comment]
There is no configuration.

**Comment by rraub** [comment]
Then how do i configure the encryption key?  is the wiki out of date then: https://github.com/InfotelGLPI/accounts/wiki/Mode-d'emploi

**Comment by rraub** [comment]
I figured it out, under the accounts tab you can click on the lock and add and encryption key there. The wiki or docs should really be updated to reflect this.

Thanks!
![screen shot 2015-12-04 at 12 44 24 pm](https://cloud.githubusercontent.com/assets/295804/11599582/f7552a6e-9a84-11e5-866b-e5fd24ea6126.png)
