### ISSUE TITLE
Self-service users (with GLPI simplified interface) cannot see any account.

### ISSUE THREAD

**Issue by jackburton79** [InfotelGLPI/accounts#50]
Plugin version 2.4.3, GLPI 9.3.3.
Self-service users (with the simplified interface) cannot see any account.
I added some accounts and linked to my user.
If I set my user's role to "self-service", I get the GLPI simplified interface. Then I click on "plugins", "accounts", and I see an empty list (screenshot attached).
If I set my user role to role which use the standard interface, I can see the accounts (under "administration" -> "accounts".
![empty account list](https://user-images.githubusercontent.com/3501519/53949529-81659380-40ca-11e9-8bbe-8d4e37ea3205.png)

**Comment by mate-infotel** [comment]
Hi,

You can't edit accounts with a simplified interface.

You can active standard interface for self-service by editing profile.

**Comment by jackburton79** [comment]
Il ven 8 mar 2019, 15:27 mate-infotel <notifications@github.com> ha scritto:

Cannot edit, and cannot see them, either?

**Comment by mate-infotel** [comment]
You need to use the super-admin profile to edit self-service profile.

**Comment by keha35** [comment]
Without answer from you we close the issue.
Feel free to reopen it if needed.
