### ISSUE TITLE
Accounts Assigned user displays only active users

### ISSUE THREAD

**Issue by vinz38500** [InfotelGLPI/accounts#53]
Hello
I'm using GLPI 9.2.4 and the accounts plugin v 2.3.3

I discovered that the Affected User list only displays Active users and I would like to 'link' some accounts to users that are also disabled in our AD (means Enabled False in user accounts) for keeping a trace.

Maybe this is available in other versions but for GLPI 9.2.x I can only use accounts 2.3.3

Thanks in advance

Vincent

**Comment by vinz38500** [comment]
Any up ?

**Comment by tsmr** [comment]
It's in GLPI (which list only active users). I close
