### ISSUE TITLE
Affichage des champs Groupe Technique et Groupe en double

### ISSUE THREAD

**Issue by bluzz04** [InfotelGLPI/accounts#55]
* Version of the plugin : 
2.5.0

* Version of your GLPI : 
9.4.4

* Steps to reproduce (which actions have you made) :
Recherche dans les comptes

* Expected result :
Les bonnes infos affichées lors dans les bonnes colonnes.

* Actual result :
Les colonnes Groupe et Groupe Technique sont affichées dans les éléments visualisés.
Ces deux champs contiennent réellement des données différentes dans la base de données.
Lors d'une recherche, ces 2 champs affichent la même info. Celle du champs de gauche.
Si Groupe et à gauche, alors ces 2 colonnes vont afficher la valeur de Groupe. Si Groupe Technique est à gauche, c'est la valeur de Groupe Technique qui s'affichera dans les 2 colonnes.
Si une seule des colonnes est affichée, les résultats sont conformes.

* URL of the page :
GLPI sur un Intranet.

* Screenshot of the problem (if pertinent) :
néant

**Comment by tsmr** [comment]
Je n'arrive pas à reproduire. A tester avec GLPI 9.4.5 ? Je clos.

**Comment by bluzz04** [comment]
Bonjour.
Effectivement, le problème ne se reproduit plus avec 9.4.5.
