### ISSUE TITLE
Error displaying the password

### ISSUE THREAD

**Issue by brunorusso** [InfotelGLPI/accounts#6]
Sometimes the plugin not show the correct characteres when decrypt password (show image).

Sometimes the password is showed correct.

What's the problem?
![error](https://cloud.githubusercontent.com/assets/430444/13289105/9bfa2c60-daed-11e5-978e-340ae1a04dd3.png)

**Comment by tsmr** [comment]
Have you use special characters like / \ ' " & into your encryption key ?

**Comment by brunorusso** [comment]
Hi!

Yes. We use !, @ or other.

**Comment by Stoatwblr** [comment]
these characters are encouraged in modern security procedures - breaking when they are used is a "very bad thing" [tm]

**Comment by pszafer** [comment]
very annoying bug...
if you don't plan to fix it, write it with big letters on main website in plugin form...

**Comment by altaviaGit** [comment]
Hello,
I am facing the same issue as @brunorusso 
When i display my passwords containing "<" char in them, the other chars before don't display

Any idea of the source of the issue / if it will be solved ?
(I also have special character like '@' in the encryption key)

Account plugin version : 2.2.0
GLPI version : 9.1

Thank you

**Comment by tsmr** [comment]
I think it's corrected now
