### ISSUE TITLE
can't add account

### ISSUE THREAD

**Issue by mmiat** [InfotelGLPI/accounts#60]
* Version of the plugin : 2.5.0
* Version of your GLPI : 9.4.5
* Steps to reproduce (which actions have you made) : when create an account and insert password, wrong encyption key message appears, but encryption field is missing
in encyption menu I've added one value
* Expected result : insert data
* Actual result : it stops with error popup
* URL of the page : http://localhost/plugins/accounts/front/account.form.php
* Screenshot of the problem (if pertinent) :
![Screenshot_17](https://user-images.githubusercontent.com/11910225/83231232-772a2c00-a18b-11ea-98f1-19d1dfc8a011.png)

**Comment by tsmr** [comment]
Hello

Have you created a encryption key before ?

**Comment by mmiat** [comment]
yes, I had, I missed to create the hash, I think it's ok now, I'll do some tests
thanks
