### ISSUE TITLE
Accounts Tab in User pages.

### ISSUE THREAD

**Issue by ggarrard** [InfotelGLPI/accounts#61]
I have what's more of a feature request than a bug. I would like to see a tab listing a user's accounts in their pages under Administration > Users. I know that now one can filter the list of accounts by the 'Affected User' and get the same list, but there are times that it would be more convenient to manage account lists from a user perspective.

* Version of the plugin : 
Accounts: Version 2.5.0

* Version of your GLPI : 
GLPI: Version 9.4.6

* Steps to reproduce (which actions have you made) :
Open Administration > Users > Some User's information

* Expected result :
A tab or other connection to the user's accounts

* Actual result :
No tab or link in existing tabs.

**Comment by tsmr** [comment]
You can see his accounts into "Used Items" tab
