### ISSUE TITLE
can't manage account plugin

### ISSUE THREAD

**Issue by gcastellarin** [InfotelGLPI/accounts#62]
Hello, since the upgrade of GLPI in 9.5.1, i can't manage the plugin "account"
Version of the plugin : 2.6.0
Version of your GLPI :  2.5.1

I can see the "account" in the environement tab, but i can't access to the parameters.

* Screenshot of the problem (if pertinent) :
![image](https://user-images.githubusercontent.com/68955902/89779776-634a6100-db10-11ea-87ea-8e824a459a53.png)

**Comment by keha35** [comment]
The probleme is in the plugin environment not accounts.
The fix is in progress.
