### ISSUE TITLE
SQL Error "1146": Table 'g9495.glpi_plugin_webapplications_webapplications' doesn't exist in query "SHOW COLUMNS FROM `glpi_plugin_webapplications_webapplications`"

### ISSUE THREAD

**Issue by jcervantes-sipecom** [InfotelGLPI/accounts#66]
Since GLPI 9.5 integrate Web Applications in the Core as Appliance, the plugin WebApplication migrate tables and delete it, these doesn't exists anymore causing some troubles like the title show when the plugin point or try to consult on these tables.

This is linking with: 

- [https://github.com/InfotelGLPI/webapplications/issues/36](https://github.com/InfotelGLPI/webapplications/issues/36)
- [https://github.com/InfotelGLPI/environment/issues/12](https://github.com/InfotelGLPI/environment/issues/12)

------------
* Version of the plugin : 
2.6.0

* Version of your GLPI : 
9.5.2

* Steps to reproduce (which actions have you made) :

1. Go to Assets
2. Click on Environment
3. Click on Accounts
4. Click on any item Acounts
5. See Error
6. Click on any item Account
7. Click on Associated Items
8. See Error

* Expected result :
Accounts point correctly to Appliances if the tables of WebApplications doesn't exists anymore, the link or Associated Items with Webapplications still persists in Appliances and the error doesn't displayed

* Actual result :
This error:
```
SQL Error "1146": Table 'g9495.glpi_plugin_webapplications_webapplications' doesn't exist in query "SHOW COLUMNS FROM `glpi_plugin_webapplications_webapplications`"
SQL Error "1146": Table 'g9495.glpi_plugin_webapplications_webapplications' doesn't exist in query "SHOW COLUMNS FROM `glpi_plugin_webapplications_webapplications`"
SQL Error "1146": Table 'g9495.glpi_plugin_webapplications_webapplications' doesn't exist in query "SELECT `glpi_plugin_webapplications_webapplications`.*, `glpi_plugin_accounts_accounts_items`.`id` AS IDD, `glpi_entities`.`id` AS entity FROM `glpi_plugin_accounts_accounts_items`, `glpi_plugin_webapplications_webapplications` LEFT JOIN `glpi_entities` ON (`glpi_entities`.`id` = `glpi_plugin_webapplications_webapplications`.`entities_id`) WHERE `glpi_plugin_webapplications_webapplications`.`id` = `glpi_plugin_accounts_accounts_items`.`items_id` AND `glpi_plugin_accounts_accounts_items`.`itemtype` = 'PluginWebapplicationsWebapplication' AND `glpi_plugin_accounts_accounts_items`.`plugin_accounts_accounts_id` = '34' ORDER BY `glpi_entities`.`completename`, `glpi_plugin_webapplications_webapplications`.`name`"
```

* URL of the page :
/plugins/accounts/front/account.php
/plugins/accounts/front/account.form.php

* Screenshot of the problem (if pertinent) :

![image](https://user-images.githubusercontent.com/56606032/96780628-72704980-13b2-11eb-96b5-d0b64e86a4d7.png)
![image](https://user-images.githubusercontent.com/56606032/96784896-ac8e1b00-13b3-11eb-8d11-9a907aaa6516.png)

**Comment by gguib** [comment]
hi,

Please check new commit on webapplication master  branch.

**Comment by jcervantes-sipecom** [comment]
Hi, Ok I will try.

**Comment by jcervantes-sipecom** [comment]
Hello, it's me again, sorry for the enormous delay.

I have the latest version of the Account plugin, but the error that I indicated before continues to appear, I don't know what it could be, maybe I'm missing some migration? or run some script to fix those references that no longer exist from WebApplications?

![image](https://user-images.githubusercontent.com/56606032/154095801-3cb9a152-dbac-4acb-8195-6876b33db92d.png)
