### ISSUE TITLE
computer.class.php

### ISSUE THREAD

**Issue by Zegordo** [InfotelGLPI/accounts#7]
hi!
i didnt see the accounts tab in /glpi/inc/computer.class.php
the other stock tabs looks like
```
   function defineTabs($options=array()) {

      $ong = array();
      $this->addDefaultFormTab($ong)
         ->addStandardTab('Item_Devices', $ong, $options)
        ->addStandardTab('ComputerDisk', $ong, $options)
```
but here dont exists tab from your addon.

Can you help to tell me, where in code i can place account tab in other position
 between other tabs?
like this:
http://image.prntscr.com/image/f5cfa31a7f3844ed9d26c5fba2cfa6df.png

**Comment by tsmr** [comment]
We cannot change order of GLPI tabs - Sorry
