### ISSUE TITLE
It's not possible to associate an Account to an inactive User

### ISSUE THREAD

**Issue by eduardomozart** [InfotelGLPI/accounts#74]
* Version of the plugin : 2.6.0

* Version of your GLPI : 9.5.5

* Steps to reproduce (which actions have you made) :

1. Set a GLPI User account "Active" field to "No".
2. Tries to associate an Account with this inactive user isn't possible.

* Expected result :

Even if a User is disabled it should be possible to associate Accounts with it.

* Actual result :

It's not possible to associate an Account to an inactive User. A workaround is enabling the user, associating the Account and disable it again.

* URL of the page :

https://glpi.example.com/plugins/accounts/front/account.form.php

* Screenshot of the problem (if pertinent) :

**Comment by tsmr** [comment]
Hello. It's a GLPI limit (the plugin use a glpi dropdown for list users)
