### ISSUE TITLE
[improvement] Make field non-mandatory

### ISSUE THREAD

**Issue by phamorais** [InfotelGLPI/accounts#77]
------------
* Version of the plugin : 
2.6.0

* Version of your GLPI : 
9.5+

When creating a new account, it is mandatory to fill in the "encryption key" field. However, I would like to register a new account without filling in a new password, as the account passwords in my scenario are controlled by Active Directory, so I don't need to register a password in GLPI.

Would it be possible to leave the filling of the field "encryption key" in a non-mandatory way?

**Comment by tsmr** [comment]
You can register your encryption key  but this is not advised

**Comment by phamorais** [comment]
@tsmr 

That doesn't solve the problem.

I understand that the best way really would be to create functionality that would allow certain fields to be non-mandatory.

In my scenario, I'm importing 700 records from an excel (generated by active directory). So I'll insert 'generic' passwords just to enable the import.

**Comment by phamorais** [comment]
Hi guys!

Would it be possible to leave the filling of the field "encryption key" in a non-mandatory way?

**Comment by phamorais** [comment]
any?

**Comment by phamorais** [comment]
I closed this issue due to the developer's lack of interest in evolving the plugin.
