### ISSUE TITLE
Corruption enregistrement

### ISSUE THREAD

**Issue by NBOLOG** [InfotelGLPI/accounts#8]
Synopsis :
Le changement de la clé de cryptage associée à l'entité racine corrompt les enregistrements des entités enfants.

Configuration : 
GLPI 90.3
Plugin Account 2.1.1

L'entité racine dispose d'une clé de chiffrement qui n'est pas héritée, propagée, dans les entités enfants.
L'entité A enfant de racine, dispose d'une clé de chiffrement propre.
L'entité B enfant de racine, dispose d'une clé de chiffrement propre.

Des comptes sont créés respectivement dans chacune des entités.
Il est possible de déchiffrer tous les mots de passe des comptes avec les clés propres à chaque entité.

La modification de la clé de cryptage de l'entité B n'entraine pas de dysfonctionnement, la modification est bien prise en compte uniquement sur les comptes de l'entité B.
La modification de la clé de cryptage de l'entité A n'entraine pas de dysfonctionnement, la modification est bien prise en compte uniquement sur les comptes de l'entité A.
La modification de la clé de cryptage de l'entité racine est bien prise en compte pour les comptes de l'entité racine. Mais cela corrompt tous les enregistrements des entités A et B. Les mots de passe sont remplacés par des caractères non imprimables.

Le fait d'initialiser le mot de passe de l'entité racine avec le mot de passe original ne corrige pas le problème.
Les mots de passes utilisés sont constitués exclusivement de caractères alpha-numériques.

**Comment by NBOLOG** [comment]
Bonjour, 
![glpi requete liste des comptes enregistres apres modification](https://cloud.githubusercontent.com/assets/21336089/18138581/c1573444-6fad-11e6-8e6d-b71c17d7feaa.PNG)
![glpi requete liste des comptes enregistres avant modification](https://cloud.githubusercontent.com/assets/21336089/18138583/c15a6a74-6fad-11e6-9229-74c79a187dc4.PNG)
![glpi requete liste des cles enregistrees apres modification](https://cloud.githubusercontent.com/assets/21336089/18138582/c1591962-6fad-11e6-8aeb-9235002c5de9.PNG)
![glpi requete liste des cles enregistrees avant modification](https://cloud.githubusercontent.com/assets/21336089/18138585/c15e5ab2-6fad-11e6-9254-b076c0a7ce2c.PNG)
![glpi requete liste des cles enregistrees requetes mysql](https://cloud.githubusercontent.com/assets/21336089/18138584/c15a8e5a-6fad-11e6-97d5-25ebbd56860d.PNG)

Nouveaux tests, mais cette fois avec des traces.

1) On voit bien dans la transaction de modification de la clé pour l'entité racine, que la modification se propage sur les trois comptes créés en test.

[Uploading Transaction Mysql GLPI - remplacement de toutes les clés.txt…]()

2) j'ai pu modifier une fois la clé de l'entité Racine sans que cela ne corrompe les comptes des entités enfants.
La seconde fois, toutes les clés ont été modifiées.
J’émets l'hypothèse que le fait de basculer entre les entités doit modifier une variable de session qui est utilisé en PHP, désolé, cela fait trop longtemps que je n'ai pas fait de code, je ne peux aller plus loin pour le moment.

**Comment by NBOLOG** [comment]
Avec la trace Mysql 
[Transaction Mysql GLPI - remplacement de toutes les clés.txt](https://github.com/InfotelGLPI/accounts/files/447882/Transaction.Mysql.GLPI.-.remplacement.de.toutes.les.cles.txt)

**Comment by NBOLOG** [comment]
Des nouvelles du front : 
La fonction de mise à jour des Hash ne prends pas en compte la notion de sous entités (oui/non). Toutes les entités enfants sont mises à jour !
Des nouveaux tests sur des entités rangées dans des arborescences différentes le confirme : seules les entités enfants sont impactées, pas celles contenues dans une autre branche à un point supérieur.
Le problème vient de la recherche des entités avec la fonction "getSonsOf" de l'objet "db" dans la fonction "updateHash" de l'objet "hash".

![getsonsof](https://cloud.githubusercontent.com/assets/21336089/18254831/2deaf116-73a2-11e6-9b92-7a9fd579b88f.PNG)

**Comment by tsmr** [comment]
Mais votre Clé racine est taguée comme étant récursive ?

![image](https://cloud.githubusercontent.com/assets/13178158/18267850/500f9952-7421-11e6-8447-f81aee8a2eeb.png)

**Comment by NBOLOG** [comment]
Merci pour le coup de main ! Non, aucune des clés n’est taguée en récursive, j’ai fait le test avec des sous entités, le problème est identique : 

-	Entité A
-	Entité A_1 sous entité de A.
-	Entité B au même niveau que A.

Dans tous les cas les clés des entités n’ont pas le tag récursif.
Chaque entité dispose de sa propre clé de chiffrement.
Si je modifie la clé de A, les enregistrements des comptes de A_1 sont aussi modifiés, donc corrompus. Par contre, les enregistrements de B ne sont pas impactés.

J’ai aussi essayé avec des profils d’utilisateurs avec des vues limitées (au niveau entité) au seul niveau de l’entité courante (A), le problème est identique.

**Comment by tsmr** [comment]
Pouvez-vous essayer cette correction ?

**Comment by NBOLOG** [comment]
Pas mieux, la valeur retournée par "$self->fields['is_recursive']" est celle résultante de la requête suivante ...?
SELECT `sons_cache`
                FROM `glpi_entities`
                WHERE `id` = 'xxxxxx'
Que je n'avais pas avant dans la trace SQL précédente. 
Je pense qu'il faudrait la remplacer la valeur de la colonne is_recursive de glpi_plugin_accounts_hashes.

**Comment by tsmr** [comment]
et maintenant ?

**Comment by NBOLOG** [comment]
C'est hashement mieux (désolé %)  )
Solution validée :+1:

**Comment by tsmr** [comment]
Ok merci pour tout ton retour. Je sortirai une version corrective.
