### ISSUE TITLE
Need to extract all entries with passwords from DB

### ISSUE THREAD

**Issue by hgpit** [InfotelGLPI/accounts#85]
Hello,

Am using Accounts plugin v3.0.2 with GLPI 10.0.2.

What I need to do is extract all account entries, including the passwords.
I have direct access to the database and know the master password.

I have tried the following, but the passwords are blank in the results:
```
SELECT 
	NULL 					AS 'collections',
	'login'					AS 'type',
	a.`name`				AS 'name',
	a.`comment`				AS 'notes',
	NULL 					AS 'fields',
	NULL 					AS 'login_uri',
	a.login 				AS 'login_username',
	AES_DECRYPT(a.`encrypted_password`,'OuRpAsSwOrD')	AS 'login_password2',
	NULL 					AS 'login_totp'
FROM glpi_plugin_accounts_accounts a
LEFT JOIN glpi_plugin_accounts_accounttypes gpaa ON gpaa.id = a.plugin_accounts_accounttypes_id AND gpaa.`entities_id` = a.`entities_id`
WHERE a.`entities_id` = 1;
```

I have read that the plugin uses AES 256, which I believe our MariaDB doesn't support, so I suspect I will need to run it in PHP.

Can anyone advise if this will be successful, or is there an easier way?

Thank you

**Comment by tsmr** [comment]
You can do this export from glpi interface

**Comment by hgpit** [comment]
How?

I already looked at GLPI's standard data export and it is unable to do this.

**Comment by tsmr** [comment]
You go on your encryption key form, and you have a tab : List of linked accounts (you can display password, if you save the encryption key temporarily before) & you can export in CSV

**Comment by polosnoopspeed** [comment]
We were on GLPIV9 with account plugin -> we could export account and password. On version 10, we could'nt. The colon is empty. Could we have more possibility to export accounts and passwords? thks
